### ISSUE TITLE
[聊天] 你这个vitepress挺好的，我找了好久中文搜索的插件，没一个好用的

### ISSUE THREAD

**Issue by pengchenggang** [devil159468/devil159468.github.io#1]
之前vuepress 有相应中文的插件
但是新的这个vitepress，有搜索都不带中文，倒是找到一个带搜索的，但是是支持老版的vitepress。

反正现在没有什么好的解决方案。实在不行，也和你一样，就不带搜索了。~~

**Comment by devil159468** [comment]
哈哈哈，我最早就没有考虑过搜索的问题，有空我试试，如果找到解决方案的话，我会同步在代码里更新~

> 之前vuepress 有相应中文的插件 但是新的这个vitepress，有搜索都不带中文，倒是找到一个带搜索的，但是是支持老版的vitepress。
> 
> 反正现在没有什么好的解决方案。实在不行，也和你一样，就不带搜索了。~~

**Comment by devil159468** [comment]
我去翻了下VitePress的源码，搜索需要使用 Algolia Docsearch 的服务，这是我暂时找到的资料

添加了这个配置之后，页面上回显示搜索的元素，但是点击该元素后会消失，我猜这需要后续在 Algolia 那边做什么操作，还在爬坑中，后续跑通之后我再回复你
`
// docs/.vitepress/config.js 添加配置（官网示例）

export default defineConfig({
    themeConfig: {
        algolia: {
		appId: '8J64VVRP8K',
		apiKey: 'a18e2f4cc5665f6602c5631fd868adfd',
		indexName: 'vitepress'
	},
    }
})
`


[VitePress config 34行](https://github.com/vuejs/vitepress/blob/main/docs/.vitepress/config.ts)

[vitepress issue 地址 #1078](https://github.com/vuejs/vitepress/issues/1078#issue-1320336910)




> 之前vuepress 有相应中文的插件 但是新的这个vitepress，有搜索都不带中文，倒是找到一个带搜索的，但是是支持老版的vitepress。
> 
> 反正现在没有什么好的解决方案。实在不行，也和你一样，就不带搜索了。~~

**Comment by devil159468** [comment]
安装 algolia 依赖：yarn add @algolia/client-search （VitePress项目翻到的）
然后重启项目，搜索按钮就生效了

后续搜索应该需要在 Algolia 配置


> 之前vuepress 有相应中文的插件 但是新的这个vitepress，有搜索都不带中文，倒是找到一个带搜索的，但是是支持老版的vitepress。
> 
> 反正现在没有什么好的解决方案。实在不行，也和你一样，就不带搜索了。~~

**Comment by devil159468** [comment]
更新了 Algolia 的配置，现在可以搜索到具体内容了，可以去[我的网站](https://devil159468.github.io/) 左上角查看效果

**Comment by pengchenggang** [comment]
我的也加上了，上他们网站上申请了个码，回复了邮件，也添加上搜索了。
https://www.vuejsdev.com/
其实还是本地支持的好，docsify就支持本地搜索，可以它的ui差一些

**Comment by beierzhijin** [comment]
> 我的也加上了，上他们网站上申请了个码，回复了邮件，也添加上搜索了。 https://www.vuejsdev.com/ 其实还是本地支持的好，docsify就支持本地搜索，可以它的ui差一些

我申请后怎么给我回的邮件内容是个这😂：
![image](https://user-images.githubusercontent.com/54610243/193815388-9f7c00b0-8a2a-42f7-983c-3305625528f3.png)

**Comment by fyzhu** [comment]
> @algolia/client-search

algolia 怎么配置的，我显示搜索按钮了，但是搜不了内容啊，内容如何上传到 algolia 呢

**Comment by fyzhu** [comment]
> 我的也加上了，上他们网站上申请了个码，回复了邮件，也添加上搜索了。 https://www.vuejsdev.com/ 其实还是本地支持的好，docsify就支持本地搜索，可以它的ui差一些
algolia 怎么配置的，我显示搜索按钮了，但是搜不了内容啊，内容如何上传到 algolia 呢

**Comment by fyzhu** [comment]
> 更新了 Algolia 的配置，现在可以搜索到具体内容了，可以去[我的网站](https://devil159468.github.io/) 左上角查看效果

algolia 怎么配置的，我显示搜索按钮了，但是搜不了内容啊，内容如何上传到 algolia 呢

**Comment by devil159468** [comment]
@fyzhu 可以参考这个issue中我回复的内容，在VitePress的情况下，需要添加Algolia配置(docs/.vitepress/config.js)，配置algolia的参数可以给algolia组织发邮件，如果通过，algolia会回复你一份配置选项，对应填写到项目里就可以了

**Comment by fyzhu** [comment]
> @fyzhu 可以参考这个issue中我回复的内容，在VitePress的情况下，需要添加Algolia配置(docs/.vitepress/config.js)，配置algolia的参数可以给algolia组织发邮件，如果通过，algolia会回复你一份配置选项，对应填写到项目里就可以了

账号配置都弄好了，主要是上传内容到 algolia，不上传的话不是搜索为空吗，后来使用 官方提供的 docker 弄好了，多谢
